### ISSUE TITLE
Clean Code

### ISSUE THREAD

**Issue by smeerws** [leonhardrobin/DodgeCube-lschnaitl#3]
Refactoring Steps

1. Define testcase (optimal automated)
2. Make sure program works, ? commited
3. Make a single change to address a code smell
4. Check if the program still works
5. Commit

Before commiting:
Check changes: git diff
Commit all changes: git commit -a !! untracked files not commited.  
No need to push every commit separately, git push will sync all local commits

**Comment by leonhardrobin** [comment]
Done!
Completed all the tasks!
